# Taskfile for Cloudflare Workers (Python) workflow
# Requires: go-task (https://taskfile.dev) and Cloudflare Wrangler (v3.60+)
# Optional: Node.js (to install wrangler), Python 3.11+

version: '3'

vars:
  # Optional env selection for wrangler environments (e.g. "production", "staging").
  ENV: '{{.ENV | default ""}}'
  PORT: '{{.PORT | default "8000"}}'

tasks:
  default:
    desc: Show common tasks
    cmds:
      - task --list

  backend:setup:
    desc: Install Python dependencies
    cmds:
      - |
        echo "==> Installing Python dependencies";
        cd backend;
        uv sync

  backend:dev:
    desc: Run local dev server (Python)
    cmds:
      - |
        echo "==> Starting local dev server";
        cd backend;
        uv run pywrangler dev

  backend:deploy:
    desc: Deploy the Worker to Cloudflare
    cmds:
      - |
        echo "==> Deploying Cloudflare Worker";
        cd backend;
        uv run pywrangler deploy

  backend:tail:
    desc: Stream Worker logs
    cmds:
      - |
        echo "==> Tailing logs";
        cd backend;
        uv run pywrangler tail --format=pretty

  backend:format:
    desc: Format backend code with Ruff
    cmds:
      - |
        echo "==> Formatting backend code";
        cd backend;
        uv run ruff format

  backend:format:check:
    desc: Check backend code formatting
    cmds:
      - |
        echo "==> Checking backend formatting";
        cd backend;
        uv run ruff format --check

  backend:lint:
    desc: Lint backend code with Ruff
    cmds:
      - |
        echo "==> Linting backend code";
        cd backend;
        uv run ruff check

  backend:lint:fix:
    desc: Lint and fix backend code
    cmds:
      - |
        echo "==> Linting and fixing backend code";
        cd backend;
        uv run ruff check --fix

  frontend:setup:
    desc: Install frontend dependencies
    cmds:
      - |
        echo "==> Installing frontend dependencies";
        cd frontend;
        bun install
  
  frontend:dev:
    desc: Run local dev server (Frontend)
    cmds:
      - |
        echo "==> Starting local dev server";
        cd frontend;
        bun run dev
        
  frontend:deploy:
    desc: Deploy frontend
    cmds:
      - |
        echo "==> Deploying frontend";
        cd frontend;
        bun run deploy

  frontend:format:
    desc: Format frontend code with Prettier
    cmds:
      - |
        echo "==> Formatting frontend code";
        cd frontend;
        bun run format

  frontend:format:check:
    desc: Check frontend code formatting with Prettier
    cmds:
      - |
        echo "==> Checking frontend formatting";
        cd frontend;
        bun run format:check

  frontend:tsc:
    desc: Check frontend code with TypeScript
    cmds:
      - |
        echo "==> Checking frontend code with TypeScript";
        cd frontend;
        bun run tsc

  frontend:lint:
    desc: Lint frontend code with ESLint
    cmds:
      - |
        echo "==> Linting frontend code";
        cd frontend;
        bun run lint

  frontend:lint:fix:
    desc: Lint and fix frontend code with ESLint
    cmds:
      - |
        echo "==> Linting and fixing frontend code";
        cd frontend;
        bun run lint:fix

  format:
    desc: Format both frontend and backend code
    cmds:
      - task backend:format
      - task frontend:format

  format:check:
    desc: Check formatting for both frontend and backend
    cmds:
      - task backend:format:check
      - task frontend:format:check

  lint:
    desc: Lint both frontend and backend code
    cmds:
      - task backend:lint
      - task frontend:lint

  lint:fix:
    desc: Lint and fix both frontend and backend code
    cmds:
      - task backend:lint:fix
      - task frontend:lint:fix

  setup:
    desc: Setup tasks
    cmds:
      - task backend:setup
      - task frontend:setup

  whoami:
    desc: Show Cloudflare account and user info
    cmds:
      - wrangler whoami

  check:
    desc: Check formatting and linting
    cmds:
      - task format:check
      - task lint
      - task frontend:tsc

  deploy:
    desc: Deploy API and/or frontend with prompts
    cmds:
      - |
        echo "==> Deploy workflow";
        
        # Prompt for API deployment
        read -p "Deploy the Cloudflare worker? y/n: " api_choice;
        
        # Prompt for frontend deployment
        read -p "Deploy the frontend? y/n: " frontend_choice;
        
        # Deploy API if user confirmed
        if [ "$api_choice" = "y" ] || [ "$api_choice" = "Y" ]; then
          echo "";
          echo "==> Deploying API...";
          task backend:deploy;
        else
          echo "==> Skipping API deployment";
        fi
        
        # Deploy frontend if user confirmed
        if [ "$frontend_choice" = "y" ] || [ "$frontend_choice" = "Y" ]; then
          echo "";
          echo "==> Deploying frontend...";
          task frontend:deploy;
        else
          echo "==> Skipping frontend deployment";
        fi
        
        echo "";
        echo "==> Deploy workflow complete!";

  