-- Update claude_label for all clusters with human-curated labels
-- Generated from cluster content analysis

UPDATE papers SET claude_label = 'Geology & Paleoclimatology' WHERE cluster_id = 0;
UPDATE papers SET claude_label = 'Water Resources & Environmental Hydrology' WHERE cluster_id = 1;
UPDATE papers SET claude_label = 'Energy Economics & Systems' WHERE cluster_id = 2;
UPDATE papers SET claude_label = 'Clinical Medicine & Risk Assessment' WHERE cluster_id = 3;
UPDATE papers SET claude_label = 'Healthcare Outcomes & Pharmacy' WHERE cluster_id = 4;
UPDATE papers SET claude_label = 'Experimental Chemistry & Modeling' WHERE cluster_id = 5;
UPDATE papers SET claude_label = 'Clinical Trials & Treatment Effects' WHERE cluster_id = 6;
UPDATE papers SET claude_label = 'Signal Processing & Acoustic Performance' WHERE cluster_id = 7;
UPDATE papers SET claude_label = 'HIV Research & Data Science' WHERE cluster_id = 8;
UPDATE papers SET claude_label = 'Social Determinants of Health' WHERE cluster_id = 9;
UPDATE papers SET claude_label = 'Soil Ecology & Biodiversity' WHERE cluster_id = 10;
UPDATE papers SET claude_label = 'Molecular Biology & Genetics' WHERE cluster_id = 11;
UPDATE papers SET claude_label = 'Materials Science at High Temperature' WHERE cluster_id = 12;
UPDATE papers SET claude_label = 'Linguistics & Language Studies' WHERE cluster_id = 13;
UPDATE papers SET claude_label = 'Aquatic Ecology & Fish Biology' WHERE cluster_id = 14;
UPDATE papers SET claude_label = 'History & Literary Studies' WHERE cluster_id = 15;
UPDATE papers SET claude_label = 'Surgical Medicine & Clinical Cases' WHERE cluster_id = 16;
UPDATE papers SET claude_label = 'Cancer Biology & microRNA' WHERE cluster_id = 17;
UPDATE papers SET claude_label = 'Pure Mathematics & Theorems' WHERE cluster_id = 18;
UPDATE papers SET claude_label = 'Educational Policy & Management' WHERE cluster_id = 19;
UPDATE papers SET claude_label = 'Speech & Communication Disorders' WHERE cluster_id = 20;
UPDATE papers SET claude_label = 'Clinical Medicine & Patient Risk' WHERE cluster_id = 21;
UPDATE papers SET claude_label = 'Tumor Biology & Cancer Treatment' WHERE cluster_id = 22;
UPDATE papers SET claude_label = 'Urban Planning & Design' WHERE cluster_id = 23;
UPDATE papers SET claude_label = 'Learning Sciences & Educational Design' WHERE cluster_id = 24;
UPDATE papers SET claude_label = 'Cell Biology & Molecular Pathways' WHERE cluster_id = 25;
UPDATE papers SET claude_label = 'Evolutionary Biology & Phylogenetics' WHERE cluster_id = 26;
UPDATE papers SET claude_label = 'Thermal Energy & Heat Transfer' WHERE cluster_id = 27;
UPDATE papers SET claude_label = 'Protein Structure & Binding' WHERE cluster_id = 28;
UPDATE papers SET claude_label = 'Cellular Therapy & Regenerative Medicine' WHERE cluster_id = 29;
UPDATE papers SET claude_label = 'Epidemiological Modeling & COVID-19' WHERE cluster_id = 30;
UPDATE papers SET claude_label = 'Quantum Physics & Spin Systems' WHERE cluster_id = 31;
UPDATE papers SET claude_label = 'Women''s Health & Maternal Care' WHERE cluster_id = 32;
UPDATE papers SET claude_label = 'Advanced Materials Science' WHERE cluster_id = 33;
UPDATE papers SET claude_label = 'Organizational Behavior & Management' WHERE cluster_id = 34;
UPDATE papers SET claude_label = 'Materials Engineering & Structural Stress' WHERE cluster_id = 35;
UPDATE papers SET claude_label = 'Antimicrobial Resistance & Microbiology' WHERE cluster_id = 36;
UPDATE papers SET claude_label = 'Urban Environmental Sociology' WHERE cluster_id = 37;
UPDATE papers SET claude_label = 'Antioxidants & In Vivo Studies' WHERE cluster_id = 38;
UPDATE papers SET claude_label = 'Computational Linguistics & NLP' WHERE cluster_id = 39;
UPDATE papers SET claude_label = 'Software Engineering & Systems' WHERE cluster_id = 40;
UPDATE papers SET claude_label = 'High Energy Physics' WHERE cluster_id = 41;
UPDATE papers SET claude_label = 'Infectious Disease & Zoonotic Transmission' WHERE cluster_id = 42;
UPDATE papers SET claude_label = 'Public Health & Risk Epidemiology' WHERE cluster_id = 43;
UPDATE papers SET claude_label = 'Medical Imaging & Diagnostics' WHERE cluster_id = 44;
UPDATE papers SET claude_label = 'Surgical Outcomes & Case Studies' WHERE cluster_id = 45;
UPDATE papers SET claude_label = 'Organic Synthesis & High-Yield Chemistry' WHERE cluster_id = 46;
UPDATE papers SET claude_label = 'Language Teaching & Pedagogy' WHERE cluster_id = 47;
UPDATE papers SET claude_label = 'Health Psychology & Well-being' WHERE cluster_id = 48;
UPDATE papers SET claude_label = 'Bone Cell Biology & In Vivo Studies' WHERE cluster_id = 49;
UPDATE papers SET claude_label = 'Mitochondrial & Cellular Bioenergetics' WHERE cluster_id = 50;
UPDATE papers SET claude_label = 'User Experience & Data Accuracy' WHERE cluster_id = 51;
UPDATE papers SET claude_label = 'Real-Time Computing & Computer Vision' WHERE cluster_id = 52;
UPDATE papers SET claude_label = 'Numerical Methods & Computational Fluid Dynamics' WHERE cluster_id = 53;
UPDATE papers SET claude_label = 'Water Engineering & Infrastructure' WHERE cluster_id = 54;
UPDATE papers SET claude_label = 'Agricultural Science & Crop Yield' WHERE cluster_id = 55;
UPDATE papers SET claude_label = 'Law & Legal Policy' WHERE cluster_id = 56;
UPDATE papers SET claude_label = 'Evidence-Based Management' WHERE cluster_id = 57;
UPDATE papers SET claude_label = 'Higher Education & Academic Science' WHERE cluster_id = 58;
UPDATE papers SET claude_label = 'Microbiology & Functional Genomics' WHERE cluster_id = 59;
UPDATE papers SET claude_label = 'Environmental Policy & Sustainability' WHERE cluster_id = 60;
UPDATE papers SET claude_label = 'Movement Science & Gait Analysis' WHERE cluster_id = 61;
UPDATE papers SET claude_label = 'Political Science & Policy Analysis' WHERE cluster_id = 62;
UPDATE papers SET claude_label = 'Computational Chemistry & Quantum Calculations' WHERE cluster_id = 63;
UPDATE papers SET claude_label = 'Model Validation & Data Analysis' WHERE cluster_id = 64;
UPDATE papers SET claude_label = 'Learning Technologies & Educational Innovation' WHERE cluster_id = 65;
UPDATE papers SET claude_label = 'Mass Spectrometry & Analytical Chemistry' WHERE cluster_id = 66;
UPDATE papers SET claude_label = 'Molecular Diagnostics & PCR Methods' WHERE cluster_id = 67;
UPDATE papers SET claude_label = 'Plant Breeding & Genomics' WHERE cluster_id = 68;
UPDATE papers SET claude_label = 'Genomics & Genetic Risk Factors' WHERE cluster_id = 69;
UPDATE papers SET claude_label = 'Control Systems & Aerospace Engineering' WHERE cluster_id = 70;
UPDATE papers SET claude_label = 'Plant Pathology & Agricultural Control' WHERE cluster_id = 71;
UPDATE papers SET claude_label = 'Pain Management & Exercise Therapy' WHERE cluster_id = 72;
UPDATE papers SET claude_label = 'High-Temperature Materials Engineering' WHERE cluster_id = 73;
UPDATE papers SET claude_label = 'Health Equity & Risk Factors' WHERE cluster_id = 74;
UPDATE papers SET claude_label = 'Environmental Chemistry & Exposure Assessment' WHERE cluster_id = 75;
UPDATE papers SET claude_label = 'Financial Risk & Market Analysis' WHERE cluster_id = 76;
UPDATE papers SET claude_label = 'Ecological Studies & Species Conservation' WHERE cluster_id = 77;
UPDATE papers SET claude_label = 'Patient Safety & Clinical Risk Management' WHERE cluster_id = 78;
UPDATE papers SET claude_label = 'Power Electronics & Electrical Control' WHERE cluster_id = 79;
UPDATE papers SET claude_label = 'Primary Care & Patient-Centered Health' WHERE cluster_id = 80;
UPDATE papers SET claude_label = 'Machine Learning & Predictive Accuracy' WHERE cluster_id = 81;
UPDATE papers SET claude_label = 'Environmental Health & Exposure Risk' WHERE cluster_id = 82;
UPDATE papers SET claude_label = 'Neuroscience & Neuroimaging' WHERE cluster_id = 83;
UPDATE papers SET claude_label = 'Theoretical Physics & Energy Systems' WHERE cluster_id = 84;
UPDATE papers SET claude_label = 'Network Computing & Time-Series Analysis' WHERE cluster_id = 85;
UPDATE papers SET claude_label = 'Oral Health & Dental Medicine' WHERE cluster_id = 86;
UPDATE papers SET claude_label = 'Radiology & Imaging Case Reports' WHERE cluster_id = 87;
UPDATE papers SET claude_label = 'Optical Materials & Photonics' WHERE cluster_id = 88;
UPDATE papers SET claude_label = 'Metabolic Disorders & Insulin Resistance' WHERE cluster_id = 89;
UPDATE papers SET claude_label = 'Social Media & Communication Studies' WHERE cluster_id = 90;
UPDATE papers SET claude_label = 'Abstract Mathematics & Operator Theory' WHERE cluster_id = 91;
UPDATE papers SET claude_label = 'Islamic Studies & Religious Education' WHERE cluster_id = 92;
UPDATE papers SET claude_label = 'Ophthalmology & Retinal Disease' WHERE cluster_id = 93;
UPDATE papers SET claude_label = 'Data Engineering & Time-Series' WHERE cluster_id = 94;
UPDATE papers SET claude_label = 'Cellular Stress & Molecular Biology' WHERE cluster_id = 95;
UPDATE papers SET claude_label = 'Cancer Survival & Risk Stratification' WHERE cluster_id = 96;
UPDATE papers SET claude_label = 'COVID-19 Infection & Clinical Management' WHERE cluster_id = 97;
UPDATE papers SET claude_label = 'Novel Materials & Smart Materials' WHERE cluster_id = 98;
UPDATE papers SET claude_label = 'Synthetic Organic Chemistry & Catalysis' WHERE cluster_id = 99;
