name: PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install backend dependencies
      run: task backend:setup

    - name: Install frontend dependencies
      run: task frontend:setup

    - name: Run checks (formatting, linting, TypeScript)
      run: task check
